<#
.SYNOPSIS
    SINGEM — Blue/Green Deployment com zero downtime.

.DESCRIPTION
    Implementa blue/green deployment usando dois containers backend
    (blue/green) e comutacao via nginx reload.

    Fluxo:
      1. Identifica qual slot esta ativo (blue ou green)
      2. Faz build e deploy no slot inativo
      3. Aguarda healthcheck do novo container
      4. Comuta nginx para o novo slot (reload)
      5. Para o container antigo (apos grace period)

.PARAMETER Action
    deploy  — Executa blue/green deployment
    status  — Mostra qual slot esta ativo
    rollback — Reverte para o slot anterior

.PARAMETER Compose
    Arquivo compose base. Padrao: docker/prod/docker-compose.yml

.PARAMETER Override
    Arquivo override (opcional).

.PARAMETER GracePeriod
    Segundos antes de parar o container antigo. Padrao: 30.

.PARAMETER WebhookUrl
    URL do webhook para notificacao (opcional).

.EXAMPLE
    .\docker-bluegreen.ps1 -Action deploy
    .\docker-bluegreen.ps1 -Action status
    .\docker-bluegreen.ps1 -Action rollback
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("deploy", "status", "rollback")]
    [string]$Action,

    [string]$Compose = "docker/prod/docker-compose.yml",
    [string]$Override = "",
    [int]$GracePeriod = 30,
    [string]$WebhookUrl = ""
)

Set-StrictMode -Version Latest

$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$projectRoot = Split-Path -Parent $scriptDir
$stateFile   = Join-Path (Join-Path $projectRoot "storage") "bluegreen-state.json"
$nginxUpstreamDir = Join-Path (Join-Path $projectRoot "docker") "upstream"

# --- Banner ----------------------------------------------------------
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " SINGEM Docker - Blue/Green Deployment" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Acao      : $Action"
Write-Host "  Projeto   : $projectRoot"
Write-Host ""

# --- State management ------------------------------------------------
function Get-DeployState {
    if (Test-Path $stateFile) {
        try {
            $content = Get-Content -Path $stateFile -Raw
            return $content | ConvertFrom-Json
        }
        catch { }
    }
    return @{ active = "blue"; previous = ""; lastDeploy = "" }
}

function Save-DeployState {
    param($State)
    $dir = Split-Path -Parent $stateFile
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    $State | ConvertTo-Json | Set-Content -Path $stateFile -Encoding UTF8
}

# --- Helpers ---------------------------------------------------------
function Test-ContainerHealthy {
    param([string]$Container, [int]$TimeoutSec = 120)
    Write-Host "  [*] Aguardando healthcheck de $Container..." -ForegroundColor Cyan
    for ($i = 1; $i -le $TimeoutSec; $i += 5) {
        $health = & docker inspect --format "{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}" $Container 2>&1
        if ($health -eq "healthy") {
            Write-Host "  [OK] $Container esta healthy." -ForegroundColor Green
            return $true
        }
        Write-Host "  [$i/$TimeoutSec] Status: $health" -ForegroundColor Gray
        Start-Sleep -Seconds 5
    }
    Write-Host "  [FAIL] $Container nao ficou healthy em ${TimeoutSec}s." -ForegroundColor Red
    return $false
}

function Send-Webhook {
    param([string]$Message, [string]$Status)
    if (-not $WebhookUrl) { return }
    try {
        $body = @{
            text   = $Message
            status = $Status
            source = "singem-bluegreen"
            time   = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
        } | ConvertTo-Json -Depth 3
        Invoke-RestMethod -Uri $WebhookUrl -Method Post -Body $body `
            -ContentType "application/json" -TimeoutSec 10 | Out-Null
    }
    catch { }
}

function Update-NginxUpstream {
    param([string]$Slot)
    $port = $(if ($Slot -eq "blue") { 3000 } else { 3001 })

    if (-not (Test-Path $nginxUpstreamDir)) {
        New-Item -ItemType Directory -Path $nginxUpstreamDir -Force | Out-Null
    }

    $upstreamConf = @"
# Auto-generated by docker-bluegreen.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Active slot: $Slot (port $port)
upstream singem_backend {
    server backend-${Slot}:3000;
}
"@

    $upstreamConf | Set-Content -Path (Join-Path $nginxUpstreamDir "backend.conf") -Encoding UTF8
    Write-Host "  [OK] Upstream nginx atualizado para slot '$Slot' (porta $port)." -ForegroundColor Green
}

function Reload-Nginx {
    $frontend = & docker ps --filter "name=singem-frontend" --format "{{.Names}}" 2>&1
    if ($frontend -and "$frontend" -match "singem-frontend") {
        & docker exec singem-frontend nginx -s reload 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  [OK] Nginx recarregado." -ForegroundColor Green
            return $true
        }
    }
    Write-Host "  [!] Nginx nao encontrado ou falha no reload." -ForegroundColor Yellow
    return $false
}

# --- STATUS ----------------------------------------------------------
if ($Action -eq "status") {
    $state = Get-DeployState
    Write-Host "  Slot ativo    : $($state.active)" -ForegroundColor White
    Write-Host "  Slot anterior : $(if ($state.previous) { $state.previous } else { 'nenhum' })"
    Write-Host "  Ultimo deploy : $(if ($state.lastDeploy) { $state.lastDeploy } else { 'nunca' })"
    Write-Host ""

    # Verificar containers
    $blue  = & docker ps --filter "name=singem-backend-blue" --format "{{.Status}}" 2>&1
    $green = & docker ps --filter "name=singem-backend-green" --format "{{.Status}}" 2>&1
    Write-Host "  backend-blue  : $(if ($blue) { $blue } else { 'parado' })"
    Write-Host "  backend-green : $(if ($green) { $green } else { 'parado' })"
    Write-Host ""
    exit 0
}

# --- DEPLOY ----------------------------------------------------------
if ($Action -eq "deploy") {
    $state = Get-DeployState
    $activeSlot   = $state.active
    $inactiveSlot = $(if ($activeSlot -eq "blue") { "green" } else { "blue" })

    Write-Host "  Slot ativo    : $activeSlot" -ForegroundColor White
    Write-Host "  Deploy para   : $inactiveSlot" -ForegroundColor Cyan
    Write-Host ""

    # 1. Build
    Write-Host "  [1/5] Build da imagem backend..." -ForegroundColor Cyan
    & docker compose -f $Compose build backend 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  [FAIL] Build falhou." -ForegroundColor Red
        Send-Webhook -Message "Blue/Green DEPLOY FALHOU: build error" -Status "error"
        exit 1
    }

    # 2. Start inactive slot
    Write-Host "  [2/5] Iniciando backend-$inactiveSlot..." -ForegroundColor Cyan
    $inactiveContainer = "singem-backend-$inactiveSlot"
    $inactivePort = $(if ($inactiveSlot -eq "blue") { "3000" } else { "3001" })

    & docker rm -f $inactiveContainer 2>&1 | Out-Null

    & docker run -d `
        --name $inactiveContainer `
        --network singem-network `
        --env-file (Join-Path $projectRoot ".env") `
        -e PORT=3000 `
        -e DB_HOST=singem-postgres `
        --health-cmd "wget -qO- http://localhost:3000/health || exit 1" `
        --health-interval 10s `
        --health-timeout 5s `
        --health-retries 5 `
        --health-start-period 30s `
        singem-backend:latest 2>&1

    if ($LASTEXITCODE -ne 0) {
        Write-Host "  [FAIL] Nao foi possivel iniciar $inactiveContainer." -ForegroundColor Red
        Send-Webhook -Message "Blue/Green DEPLOY FALHOU: container start error ($inactiveSlot)" -Status "error"
        exit 1
    }

    # 3. Wait for healthy
    Write-Host "  [3/5] Aguardando healthcheck..." -ForegroundColor Cyan
    $healthy = Test-ContainerHealthy -Container $inactiveContainer -TimeoutSec 120
    if (-not $healthy) {
        Write-Host "  [FAIL] Container nao ficou healthy. Removendo..." -ForegroundColor Red
        & docker rm -f $inactiveContainer 2>&1 | Out-Null
        Send-Webhook -Message "Blue/Green DEPLOY FALHOU: healthcheck timeout ($inactiveSlot)" -Status "error"
        exit 1
    }

    # 4. Switch nginx upstream
    Write-Host "  [4/5] Comutando nginx para $inactiveSlot..." -ForegroundColor Cyan
    Update-NginxUpstream -Slot $inactiveSlot
    $reloaded = Reload-Nginx

    # 5. Grace period + stop old
    Write-Host "  [5/5] Grace period de ${GracePeriod}s antes de parar $activeSlot..." -ForegroundColor Cyan
    Start-Sleep -Seconds $GracePeriod
    $oldContainer = "singem-backend-$activeSlot"
    & docker stop $oldContainer 2>&1 | Out-Null

    # Save state
    $newState = @{
        active     = $inactiveSlot
        previous   = $activeSlot
        lastDeploy = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
    }
    Save-DeployState -State $newState

    Write-Host ""
    Write-Host "  [OK] Deploy blue/green concluido!" -ForegroundColor Green
    Write-Host "  Slot ativo: $inactiveSlot" -ForegroundColor White
    Write-Host ""
    Send-Webhook -Message "Blue/Green deploy concluido: $activeSlot -> $inactiveSlot" -Status "ok"
    exit 0
}

# --- ROLLBACK --------------------------------------------------------
if ($Action -eq "rollback") {
    $state = Get-DeployState

    if (-not $state.previous) {
        Write-Host "  [FAIL] Nenhum deploy anterior registrado para rollback." -ForegroundColor Red
        exit 1
    }

    $currentSlot  = $state.active
    $rollbackSlot = $state.previous

    Write-Host "  Rollback: $currentSlot -> $rollbackSlot" -ForegroundColor Yellow

    $rollbackContainer = "singem-backend-$rollbackSlot"
    $containerExists = & docker ps -a --filter "name=$rollbackContainer" --format "{{.Names}}" 2>&1

    if (-not $containerExists) {
        Write-Host "  [FAIL] Container $rollbackContainer nao existe." -ForegroundColor Red
        exit 1
    }

    # Start the previous container
    & docker start $rollbackContainer 2>&1 | Out-Null
    $healthy = Test-ContainerHealthy -Container $rollbackContainer -TimeoutSec 90

    if (-not $healthy) {
        Write-Host "  [FAIL] Container de rollback nao ficou healthy." -ForegroundColor Red
        exit 1
    }

    # Switch upstream
    Update-NginxUpstream -Slot $rollbackSlot
    Reload-Nginx

    # Stop current
    Start-Sleep -Seconds 10
    & docker stop "singem-backend-$currentSlot" 2>&1 | Out-Null

    $newState = @{
        active     = $rollbackSlot
        previous   = $currentSlot
        lastDeploy = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
    }
    Save-DeployState -State $newState

    Write-Host ""
    Write-Host "  [OK] Rollback concluido! Slot ativo: $rollbackSlot" -ForegroundColor Green
    Write-Host ""
    Send-Webhook -Message "Blue/Green ROLLBACK: $currentSlot -> $rollbackSlot" -Status "warning"
    exit 0
}
